import type { AssessmentInput } from "../validation/assessment";
export const fixtureVersion = "2026-09-v1";
const businesses = [
  [
    "Caledon Furniture Works",
    "Furniture",
    "Refurbishment",
    "Central Scotland",
    "Furniture refurbishment and take-back",
    "Supplier concentration",
    82,
    72,
    120000,
  ],
  [
    "Forth Equipment Services",
    "Equipment rental",
    "Product-as-a-Service",
    "Central Scotland",
    "A maintained equipment fleet with recurring service revenue",
    "Capital access",
    88,
    86,
    380000,
  ],
  [
    "North Coast Textiles",
    "Textiles",
    "Remanufacturing",
    "North & Islands",
    "Recovered textile feedstock for remanufactured workwear",
    "Customer evidence",
    35,
    38,
    240000,
  ],
  [
    "Tay Precision Components",
    "Manufacturing",
    "Remanufacturing",
    "Central Scotland",
    "Return and rebuild industrial pump components",
    "Skills & capability",
    76,
    75,
    280000,
  ],
  [
    "Solway Food Collective",
    "Food",
    "Waste-to-value",
    "South Scotland",
    "Convert food production by-products into new ingredients",
    "Operating capacity",
    68,
    63,
    95000,
  ],
  [
    "Clyde Material Exchange",
    "Construction",
    "Reuse",
    "Central Scotland",
    "Match reusable construction materials with local buyers",
    "Customer evidence",
    59,
    57,
    65000,
  ],
  [
    "Moray Device Renewal",
    "Electronics",
    "Repair",
    "North & Islands",
    "Repair and lease refurbished business devices",
    "Capital access",
    80,
    79,
    155000,
  ],
  [
    "Border Home Essentials",
    "Consumer goods",
    "Lifetime extension",
    "South Scotland",
    "Repair kits and spare parts for household products",
    "Unit economics",
    55,
    48,
    45000,
  ],
  [
    "Fife Return Packaging",
    "Packaging",
    "Closed-loop material use",
    "Central Scotland",
    "Reusable transport packaging with a local return loop",
    "Supplier concentration",
    85,
    81,
    310000,
  ],
  [
    "Highland Industrial Care",
    "Industrial services",
    "Lifetime extension",
    "North & Islands",
    "Inspection and repair to extend industrial equipment life",
    "Skills & capability",
    77,
    73,
    165000,
  ],
  [
    "Lothian Shared Tools",
    "Equipment rental",
    "Sharing",
    "Central Scotland",
    "A shared professional tool library for small contractors",
    "Operating capacity",
    62,
    60,
    115000,
  ],
  [
    "Galloway Living Studio",
    "Furniture",
    "Take-back",
    "South Scotland",
    "Take-back and repair for locally made furniture",
    "Customer evidence",
    47,
    44,
    75000,
  ],
] as const;
export function seedInputs(): AssessmentInput[] {
  return businesses.map(
    (
      [
        name,
        sector,
        model,
        region,
        opportunity,
        barrier,
        demand,
        quality,
        capex,
      ],
      i,
    ) => ({
      name,
      sector,
      region,
      size: i % 3 === 0 ? "Medium" : i % 3 === 1 ? "Small" : "Micro",
      businessModel: [model, ...(i === 0 ? ["Take-back" as const] : [])],
      summary: `${name} is a fictional Scottish ${sector.toLowerCase()} business used to test a commercial decision. Its existing model relies on one-off sales and purchased materials.`,
      operatingModel:
        "One-off sales with direct delivery, purchased materials and a small specialist operations team.",
      opportunity,
      customerEvidence:
        demand >= 75
          ? "Synthetic pilot: repeat buyers have indicated demand. Pricing and long-term retention need independent validation."
          : "Synthetic interviews indicate interest. Signed commitments and willingness-to-pay evidence are still missing.",
      resourceDependencies:
        i === 0
          ? "Timber and fittings: 68% of critical materials come from one supplier. Recovered timber could reduce exposure."
          : "Specialist materials, energy and regional distribution partners. Alternative suppliers require qualification.",
      barriers: [
        barrier,
        ...(quality < 60 ? ["Customer evidence" as const] : []),
      ].filter((v, j, a) => a.indexOf(v) === j),
      baseline: {
        revenue: 600000 + i * 95000,
        material: 180000 + i * 27000,
        labour: 150000 + i * 21000,
        energy: 36000 + i * 2500,
        maintenance: 18000 + i * 1300,
        overhead: 105000 + i * 17000,
      },
      scenario: {
        revenueChange: i === 2 ? 3 : 8 + (i % 4) * 2,
        materialSaving: 20 + (i % 5) * 6,
        energySaving: 10 + (i % 4) * 3,
        recurringRevenue: i === 1 ? 280000 : 30000 + i * 5500,
        extraLabour: 28000 + i * 2800,
        extraOperating: 18000 + i * 2200,
        capex,
        workingCapital: 18000 + i * 2500,
        residualValue: Math.round(capex * 0.12),
        retention: 70 + (i % 5) * 5,
        supplierShock: i === 2 ? 18 : 5,
      },
      factors: {
        demand,
        market: Math.max(20, demand - 8),
        capability: 65 + (i % 5) * 6,
        readiness: 58 + (i % 5) * 7,
        supplierConcentration: i === 0 ? 68 : 30 + (i % 5) * 11,
        importDependency: 25 + (i % 4) * 14,
        volatility: i === 2 ? 85 : 28 + (i % 5) * 8,
        substitution: 48 + (i % 5) * 9,
        repairability: 60 + (i % 5) * 8,
        reuse: 65 + (i % 4) * 10,
        diversity: 45 + (i % 5) * 8,
        retention: 70 + (i % 5) * 5,
        flexibility: 62 + (i % 4) * 8,
        scalability: 60 + (i % 5) * 7,
        traction: Math.max(15, demand - 12),
        resourceSecurity: 55 + (i % 5) * 8,
        evidence: quality,
      },
    }),
  );
}
