import type { MaterialStream } from "./types";

/**
 * Material streams for the 12 demonstrator organisations.
 *
 * Authored to be internally consistent with each organisation's sector and
 * circular models (see seed-data.ts). Supply = what the organisation can put
 * back into circulation; demand = circular inputs it is seeking. The engine
 * pairs compatible streams across organisations into opportunity matches.
 *
 * ALL VALUES ARE ILLUSTRATIVE.
 */
export const MATERIAL_STREAMS: MaterialStream[] = [
  // ── Timber & board ───────────────────────────────────────────────────────
  {
    id: "caledon-s-board",
    orgId: "caledon-furniture-works",
    direction: "supply",
    family: "Timber & board",
    material: "Reclaimed office furniture board",
    annualVolumeTonnes: 320,
    valuePerTonne: 240,
    readiness: 68,
    grade: "B",
    currentFate: "Downcycled or landfilled at end of contract",
  },
  {
    id: "caledon-d-board",
    orgId: "caledon-furniture-works",
    direction: "demand",
    family: "Timber & board",
    material: "Refurbishment-grade board & panels",
    annualVolumeTonnes: 180,
    valuePerTonne: 245,
    readiness: 64,
    minGrade: "B",
    specNeeded: "De-laminated board, ≥18mm, FSC where possible",
  },
  {
    id: "highland-s-timber",
    orgId: "highland-timber-joinery",
    direction: "supply",
    family: "Timber & board",
    material: "Reclaimed structural timber",
    annualVolumeTonnes: 260,
    valuePerTonne: 310,
    readiness: 60,
    grade: "B",
    currentFate: "Skipped or chipped on site",
  },
  {
    id: "highland-d-timber",
    orgId: "highland-timber-joinery",
    direction: "demand",
    family: "Timber & board",
    material: "Reclaimed timber & board for reuse builds",
    annualVolumeTonnes: 300,
    valuePerTonne: 300,
    readiness: 58,
    minGrade: "C",
    specNeeded: "Softwood or board, nail-free, strength-graded",
  },

  // ── Textiles & fibre ─────────────────────────────────────────────────────
  {
    id: "borders-s-yarn",
    orgId: "borders-woollen-mill",
    direction: "supply",
    family: "Textiles & fibre",
    material: "Wool yarn offcuts & ends",
    annualVolumeTonnes: 48,
    valuePerTonne: 1200,
    readiness: 72,
    grade: "A",
    currentFate: "Baled and exported for low-value reprocessing",
  },
  {
    id: "borders-d-wool",
    orgId: "borders-woollen-mill",
    direction: "demand",
    family: "Textiles & fibre",
    material: "Reclaimed wool for re-spinning",
    annualVolumeTonnes: 36,
    valuePerTonne: 1150,
    readiness: 66,
    minGrade: "B",
    specNeeded: "Clean carded wool, single-fibre, ≤10% synthetic",
  },
  {
    id: "northcoast-s-fibre",
    orgId: "north-coast-textiles",
    direction: "supply",
    family: "Textiles & fibre",
    material: "Recovered wool fibre (shoddy)",
    annualVolumeTonnes: 90,
    valuePerTonne: 900,
    readiness: 70,
    grade: "B",
    currentFate: "Mixed textile waste to RDF",
  },
  {
    id: "northcoast-d-feedstock",
    orgId: "north-coast-textiles",
    direction: "demand",
    family: "Textiles & fibre",
    material: "Reclaimed wool feedstock for remanufacture",
    annualVolumeTonnes: 120,
    valuePerTonne: 950,
    readiness: 74,
    minGrade: "C",
    specNeeded: "Wool-rich reclaimed fibre, baled",
  },

  // ── Metals & alloys ──────────────────────────────────────────────────────
  {
    id: "marine-s-steel",
    orgId: "aberdeen-marine-rentals",
    direction: "supply",
    family: "Metals & alloys",
    material: "Decommissioned subsea steel",
    annualVolumeTonnes: 540,
    valuePerTonne: 420,
    readiness: 64,
    grade: "B",
    currentFate: "Sold to scrap merchant / exported",
  },
  {
    id: "clyde-s-alloy",
    orgId: "clyde-precision-manufacturing",
    direction: "supply",
    family: "Metals & alloys",
    material: "Alloy swarf & reclaimed castings",
    annualVolumeTonnes: 180,
    valuePerTonne: 1400,
    readiness: 72,
    grade: "A",
    currentFate: "Sold as mixed scrap",
  },
  {
    id: "clyde-d-alloy",
    orgId: "clyde-precision-manufacturing",
    direction: "demand",
    family: "Metals & alloys",
    material: "Reclaimed alloy bar & castings for remanufacture",
    annualVolumeTonnes: 160,
    valuePerTonne: 1500,
    readiness: 70,
    minGrade: "B",
    specNeeded: "Segregated alloy, certified grade & provenance",
  },
  {
    id: "forth-s-steel",
    orgId: "forth-equipment-services",
    direction: "supply",
    family: "Metals & alloys",
    material: "End-of-life steel plant",
    annualVolumeTonnes: 220,
    valuePerTonne: 360,
    readiness: 58,
    grade: "C",
    currentFate: "Auctioned or scrapped",
  },

  // ── Electronics & components ─────────────────────────────────────────────
  {
    id: "granite-s-modules",
    orgId: "granite-city-electronics",
    direction: "supply",
    family: "Electronics & components",
    material: "Harvested modules & boards",
    annualVolumeTonnes: 26,
    valuePerTonne: 3800,
    readiness: 70,
    grade: "B",
    currentFate: "Sent to WEEE recycler",
  },
  {
    id: "granite-d-components",
    orgId: "granite-city-electronics",
    direction: "demand",
    family: "Electronics & components",
    material: "Refurb-grade components & modules",
    annualVolumeTonnes: 20,
    valuePerTonne: 4000,
    readiness: 66,
    minGrade: "C",
    specNeeded: "Tested boards with documentation",
  },
  {
    id: "dundee-s-boards",
    orgId: "dundee-appliance-loop",
    direction: "supply",
    family: "Electronics & components",
    material: "Appliance boards & harnesses",
    annualVolumeTonnes: 34,
    valuePerTonne: 2600,
    readiness: 64,
    grade: "C",
    currentFate: "WEEE shredding",
  },
  {
    id: "dundee-d-spares",
    orgId: "dundee-appliance-loop",
    direction: "demand",
    family: "Electronics & components",
    material: "Refurbishment spares & components",
    annualVolumeTonnes: 28,
    valuePerTonne: 2800,
    readiness: 68,
    minGrade: "C",
    specNeeded: "Working modules, graded and logged",
  },

  // ── Polymers & plastics ──────────────────────────────────────────────────
  {
    id: "lothian-s-resin",
    orgId: "lothian-packaging",
    direction: "supply",
    family: "Polymers & plastics",
    material: "Recovered polymer resin (rPET/rPP)",
    annualVolumeTonnes: 410,
    valuePerTonne: 620,
    readiness: 74,
    grade: "B",
    currentFate: "Baled for third-party recycler",
  },
  {
    id: "lothian-d-polymer",
    orgId: "lothian-packaging",
    direction: "demand",
    family: "Polymers & plastics",
    material: "Post-industrial polymer for closed loop",
    annualVolumeTonnes: 300,
    valuePerTonne: 600,
    readiness: 70,
    minGrade: "C",
    specNeeded: "Clean, sorted by polymer type",
  },
  {
    id: "dundee-s-polymer",
    orgId: "dundee-appliance-loop",
    direction: "supply",
    family: "Polymers & plastics",
    material: "Appliance polymer housings",
    annualVolumeTonnes: 60,
    valuePerTonne: 420,
    readiness: 60,
    grade: "C",
    currentFate: "Shredded or landfilled",
  },

  // ── Food & organic ───────────────────────────────────────────────────────
  {
    id: "tay-s-organic",
    orgId: "tay-valley-food-co",
    direction: "supply",
    family: "Food & organic",
    material: "Spent grain & fruit pomace",
    annualVolumeTonnes: 950,
    valuePerTonne: 60,
    readiness: 66,
    grade: "B",
    currentFate: "Low-value animal feed or disposal",
  },

  // ── Glass & packaging ────────────────────────────────────────────────────
  {
    id: "lothian-s-packaging",
    orgId: "lothian-packaging",
    direction: "supply",
    family: "Glass & packaging",
    material: "Recovered fibre & packaging",
    annualVolumeTonnes: 280,
    valuePerTonne: 150,
    readiness: 72,
    grade: "B",
    currentFate: "Materials recovery facility",
  },
  {
    id: "tay-d-packaging",
    orgId: "tay-valley-food-co",
    direction: "demand",
    family: "Glass & packaging",
    material: "Recycled glass & packaging",
    annualVolumeTonnes: 140,
    valuePerTonne: 160,
    readiness: 64,
    minGrade: "C",
    specNeeded: "Food-safe recycled packaging",
  },

  // ── Equipment & assets ───────────────────────────────────────────────────
  {
    id: "marine-s-equipment",
    orgId: "aberdeen-marine-rentals",
    direction: "supply",
    family: "Equipment & assets",
    material: "Retired marine equipment units",
    annualVolumeTonnes: 120,
    valuePerTonne: 2200,
    readiness: 62,
    grade: "B",
    currentFate: "Auctioned at end of charter",
  },
  {
    id: "forth-s-plant",
    orgId: "forth-equipment-services",
    direction: "supply",
    family: "Equipment & assets",
    material: "Off-hire plant & tools",
    annualVolumeTonnes: 150,
    valuePerTonne: 1800,
    readiness: 66,
    grade: "B",
    currentFate: "Resold or scrapped",
  },
  {
    id: "forth-d-cores",
    orgId: "forth-equipment-services",
    direction: "demand",
    family: "Equipment & assets",
    material: "Remanufacture-ready plant cores",
    annualVolumeTonnes: 90,
    valuePerTonne: 1900,
    readiness: 64,
    minGrade: "C",
    specNeeded: "Repairable units with service history",
  },
  {
    id: "stirling-s-tools",
    orgId: "stirling-toolshare",
    direction: "supply",
    family: "Equipment & assets",
    material: "Worn shared tools",
    annualVolumeTonnes: 22,
    valuePerTonne: 1200,
    readiness: 58,
    grade: "C",
    currentFate: "Discarded when worn",
  },
  {
    id: "stirling-d-tools",
    orgId: "stirling-toolshare",
    direction: "demand",
    family: "Equipment & assets",
    material: "Repairable tools & equipment",
    annualVolumeTonnes: 28,
    valuePerTonne: 1250,
    readiness: 70,
    minGrade: "C",
    specNeeded: "Repairable power and hand tools",
  },
];
