import type { AssessmentInputs } from "../domain/scoring/types";
import type { FinancialBaseline, ScenarioAssumptions } from "../domain/scenarios/model";
import type {
  EvidenceStatus,
  EvidenceType,
  AssessmentStage,
} from "../domain/constants";

/**
 * Deterministic synthetic seed data — 12 Scottish business scenarios.
 *
 * ALL DATA IS SYNTHETIC. These businesses are illustrative and do not
 * represent real companies. Values are chosen to give a realistic spread
 * across commercial viability, capital requirement, resilience, evidence
 * quality, investor readiness and circular model.
 */

/** Neutral baseline for assessment inputs; specs override the distinctive fields. */
const NEUTRAL: AssessmentInputs = {
  marketAttractiveness: 55,
  customerDemand: 55,
  revenuePotential: 55,
  marginPotential: 55,
  scalability: 50,
  operationalFeasibility: 55,
  capexRequirement: 250000,
  annualRevenueUplift: 150000,
  annualCostSaving: 80000,
  paybackYears: 3,
  commercialRisk: 45,
  resourceExposure: 45,
  supplierConcentration: 45,
  materialDependency: 45,
  importExposure: 40,
  resourcePriceVolatility: 45,
  substitutionOptions: 50,
  repairability: 50,
  reuseOpportunity: 50,
  revenueDiversity: 50,
  recurringRevenueShare: 25,
  customerRetention: 60,
  operationalFlexibility: 55,
  customerEvidence: 50,
  marketValidation: 50,
  commercialTraction: 45,
  unitEconomics: 50,
  managementCapability: 55,
  operatingCapability: 55,
  capitalClarity: 50,
  riskUnderstanding: 50,
  circularPropositionClarity: 55,
  dataQuality: 50,
  materialRecoveryPotential: 50,
  lifetimeExtensionPotential: 50,
  circularRevenueModelStrength: 50,
  supplyChainBenefit: 50,
  resourceSecurityBenefit: 50,
  evidenceCoverage: 50,
  evidenceRecency: 50,
  evidenceIndependence: 45,
  evidenceVerification: 45,
};

function mkInputs(overrides: Partial<AssessmentInputs>): AssessmentInputs {
  return { ...NEUTRAL, ...overrides };
}

export interface EvidenceSpec {
  type: EvidenceType;
  description: string;
  source: string;
  confidence: number;
  linkedArea: string;
  status: EvidenceStatus;
  /** Months before the seed reference date. */
  agedMonths: number;
}

export interface ResourceDepSpec {
  material: string;
  criticality: "High" | "Medium" | "Low";
  annualSpend: number;
  volatility: "High" | "Medium" | "Low";
  notes: string;
}

export interface SupplierRiskSpec {
  supplier: string;
  category: string;
  shareOfSupplyPct: number;
  region: string;
  riskLevel: "High" | "Medium" | "Low";
}

export interface BusinessSpec {
  id: string;
  name: string;
  sector: string;
  companySize: string;
  region: string;
  description: string;
  currentOperatingModel: string;
  currentRevenueModel: string;
  productsServices: string;
  customerModel: string;
  commercialPressures: string;
  stage: AssessmentStage;
  circularModels: string[];
  opportunitySummary: string;
  commercialRationale: string;
  baseline: FinancialBaseline;
  circular: ScenarioAssumptions;
  inputs: AssessmentInputs;
  evidence: EvidenceSpec[];
  resourceDeps: ResourceDepSpec[];
  supplierRisks: SupplierRiskSpec[];
}

export const BUSINESSES: BusinessSpec[] = [
  {
    id: "caledon-furniture-works",
    name: "Caledon Furniture Works",
    sector: "Furniture",
    companySize: "Small (10-49)",
    region: "Glasgow",
    description:
      "Contract furniture maker supplying offices, hospitality and public-sector clients across the central belt.",
    currentOperatingModel:
      "Batch manufacture of new furniture from virgin timber and board, with limited end-of-life involvement.",
    currentRevenueModel: "One-off product sales via framework contracts and direct tenders.",
    productsServices: "Desks, seating, storage and soft-seating for commercial interiors.",
    customerModel: "B2B — facilities managers, interior fit-out firms and public bodies.",
    commercialPressures:
      "Rising board and foam prices, procurement pressure on embodied carbon, and clients asking for take-back at end of contract.",
    stage: "In Review",
    circularModels: ["Refurbishment", "Take-back"],
    opportunitySummary:
      "Launch a refurbishment and take-back line: recover used furniture from clients, refurbish it and resell or re-lease it under framework agreements.",
    commercialRationale:
      "Refurbishment margins are strong and take-back deepens client relationships, but the model concentrates supply of reclaimable stock with a few large clients.",
    baseline: {
      revenue: 3200000,
      materialCost: 1350000,
      energyCost: 190000,
      labourCost: 820000,
      opex: 430000,
      maintenanceCost: 120000,
      workingCapital: 480000,
    },
    circular: {
      revenueDeltaPct: 16,
      materialCostDeltaPct: -14,
      energyCostDeltaPct: 4,
      labourCostDeltaPct: 9,
      opexDeltaPct: 6,
      maintenanceDeltaPct: 8,
      capex: 340000,
      workingCapitalDelta: 90000,
      recurringRevenueSharePct: 28,
      customerRetentionPct: 78,
      residualValue: 140000,
    },
    inputs: mkInputs({
      marketAttractiveness: 68,
      customerDemand: 74,
      revenuePotential: 66,
      marginPotential: 72,
      operationalFeasibility: 66,
      scalability: 58,
      capexRequirement: 340000,
      annualRevenueUplift: 512000,
      annualCostSaving: 189000,
      paybackYears: 2.4,
      commercialRisk: 44,
      supplierConcentration: 72,
      materialDependency: 58,
      resourcePriceVolatility: 58,
      recurringRevenueShare: 28,
      customerRetention: 78,
      revenueDiversity: 52,
      repairability: 74,
      reuseOpportunity: 78,
      customerEvidence: 66,
      marketValidation: 58,
      commercialTraction: 55,
      unitEconomics: 60,
      managementCapability: 62,
      capitalClarity: 58,
      circularPropositionClarity: 72,
      materialRecoveryPotential: 70,
      lifetimeExtensionPotential: 76,
      circularRevenueModelStrength: 66,
      supplyChainBenefit: 62,
      resourceSecurityBenefit: 60,
      evidenceCoverage: 60,
      evidenceRecency: 62,
      evidenceIndependence: 52,
      evidenceVerification: 55,
    }),
    evidence: [
      {
        type: "Customer interview",
        description: "Six framework clients confirmed appetite for refurbished stock at ~20% discount to new.",
        source: "Internal account management",
        confidence: 62,
        linkedArea: "Customer demand",
        status: "Provisional",
        agedMonths: 3,
      },
      {
        type: "Pilot data",
        description: "12-desk refurbishment pilot achieved 41% gross margin.",
        source: "Operations trial Q1",
        confidence: 70,
        linkedArea: "Margin potential",
        status: "Verified",
        agedMonths: 4,
      },
      {
        type: "Supplier quote",
        description: "Foam and fabric re-upholstery input pricing from two suppliers.",
        source: "Procurement",
        confidence: 58,
        linkedArea: "Material cost",
        status: "Provisional",
        agedMonths: 2,
      },
    ],
    resourceDeps: [
      {
        material: "Engineered board (MDF/chipboard)",
        criticality: "High",
        annualSpend: 610000,
        volatility: "Medium",
        notes: "Primary carcass material; price-linked to timber and resin markets.",
      },
      {
        material: "Upholstery foam",
        criticality: "Medium",
        annualSpend: 210000,
        volatility: "High",
        notes: "Petrochemical-linked; volatile pricing.",
      },
    ],
    supplierRisks: [
      {
        supplier: "Central Board Supplies",
        category: "Engineered board",
        shareOfSupplyPct: 64,
        region: "UK",
        riskLevel: "High",
      },
      {
        supplier: "Clyde Textiles",
        category: "Upholstery fabric",
        shareOfSupplyPct: 38,
        region: "UK",
        riskLevel: "Medium",
      },
    ],
  },
  {
    id: "forth-equipment-services",
    name: "Forth Equipment Services",
    sector: "Equipment Rental",
    companySize: "Medium (50-249)",
    region: "Edinburgh",
    description:
      "Supplier of specialist plant and access equipment to construction and events sectors.",
    currentOperatingModel: "Sells and services equipment; a small hire fleet operates alongside.",
    currentRevenueModel: "Capital sales with aftermarket parts and servicing.",
    productsServices: "Access platforms, generators, pumps and site equipment.",
    customerModel: "B2B — contractors, event companies and facilities operators.",
    commercialPressures:
      "Customers deferring capital purchases; demand for flexible access to equipment rather than ownership.",
    stage: "Investment Ready",
    circularModels: ["Product-as-a-Service", "Leasing"],
    opportunitySummary:
      "Shift core fleet to a Product-as-a-Service model: customers pay for guaranteed uptime, Forth retains ownership, maintains and redeploys assets.",
    commercialRationale:
      "PaaS converts one-off sales into recurring, higher-margin revenue and improves asset utilisation; it needs upfront capital to build the managed fleet.",
    baseline: {
      revenue: 9800000,
      materialCost: 3600000,
      energyCost: 320000,
      labourCost: 2400000,
      opex: 1300000,
      maintenanceCost: 640000,
      workingCapital: 1500000,
    },
    circular: {
      revenueDeltaPct: 12,
      materialCostDeltaPct: -8,
      energyCostDeltaPct: 3,
      labourCostDeltaPct: 6,
      opexDeltaPct: 5,
      maintenanceDeltaPct: 14,
      capex: 1800000,
      workingCapitalDelta: 260000,
      recurringRevenueSharePct: 64,
      customerRetentionPct: 86,
      residualValue: 900000,
    },
    inputs: mkInputs({
      marketAttractiveness: 72,
      customerDemand: 70,
      revenuePotential: 74,
      marginPotential: 68,
      operationalFeasibility: 70,
      scalability: 72,
      capexRequirement: 1800000,
      annualRevenueUplift: 1176000,
      annualCostSaving: 240000,
      paybackYears: 3.6,
      commercialRisk: 40,
      resourceExposure: 38,
      supplierConcentration: 42,
      materialDependency: 40,
      resourcePriceVolatility: 40,
      substitutionOptions: 60,
      recurringRevenueShare: 64,
      customerRetention: 86,
      revenueDiversity: 68,
      operationalFlexibility: 70,
      customerEvidence: 74,
      marketValidation: 70,
      commercialTraction: 72,
      unitEconomics: 72,
      managementCapability: 74,
      operatingCapability: 72,
      capitalClarity: 70,
      riskUnderstanding: 68,
      circularPropositionClarity: 76,
      dataQuality: 66,
      materialRecoveryPotential: 58,
      lifetimeExtensionPotential: 72,
      circularRevenueModelStrength: 80,
      supplyChainBenefit: 66,
      resourceSecurityBenefit: 64,
      evidenceCoverage: 72,
      evidenceRecency: 70,
      evidenceIndependence: 66,
      evidenceVerification: 68,
    }),
    evidence: [
      {
        type: "Financial record",
        description: "Existing hire fleet runs at 74% utilisation and 58% gross margin.",
        source: "Management accounts FY",
        confidence: 82,
        linkedArea: "Unit economics",
        status: "Verified",
        agedMonths: 5,
      },
      {
        type: "Customer interview",
        description: "Nine key accounts prefer uptime-based contracts to ownership.",
        source: "Sales discovery",
        confidence: 72,
        linkedArea: "Customer demand",
        status: "Verified",
        agedMonths: 4,
      },
      {
        type: "External benchmark",
        description: "PaaS conversion benchmarks from equipment-rental sector.",
        source: "Industry report",
        confidence: 64,
        linkedArea: "Market validation",
        status: "Provisional",
        agedMonths: 8,
      },
    ],
    resourceDeps: [
      {
        material: "Steel & hydraulic components",
        criticality: "Medium",
        annualSpend: 1400000,
        volatility: "Medium",
        notes: "Fleet build and spares.",
      },
      {
        material: "Diesel / power units",
        criticality: "Medium",
        annualSpend: 520000,
        volatility: "High",
        notes: "Being displaced by electric units over time.",
      },
    ],
    supplierRisks: [
      {
        supplier: "Grampian Plant OEM",
        category: "Equipment",
        shareOfSupplyPct: 44,
        region: "EU",
        riskLevel: "Medium",
      },
      {
        supplier: "Lothian Spares",
        category: "Parts",
        shareOfSupplyPct: 30,
        region: "UK",
        riskLevel: "Low",
      },
    ],
  },
  {
    id: "north-coast-textiles",
    name: "North Coast Textiles",
    sector: "Textiles",
    companySize: "Small (10-49)",
    region: "Inverness",
    description:
      "Weaver and finisher producing woven textiles for fashion and interiors.",
    currentOperatingModel: "Buys virgin yarn, weaves and finishes fabric for brand customers.",
    currentRevenueModel: "Wholesale fabric sales by the metre.",
    productsServices: "Woven wool and blended fabrics.",
    customerModel: "B2B — fashion houses and interior brands.",
    commercialPressures:
      "Volatile virgin-wool prices, thin margins and pressure from brands for recycled-content fabric.",
    stage: "Draft",
    circularModels: ["Closed-loop material recovery", "Remanufacturing"],
    opportunitySummary:
      "Establish a textile recovery and remanufacturing line reprocessing post-industrial and returned textiles into new yarn and fabric.",
    commercialRationale:
      "Recovered fibre reduces exposure to volatile virgin-wool prices and opens recycled-content premium products — but demand evidence is thin and processing yields are unproven.",
    baseline: {
      revenue: 2100000,
      materialCost: 1080000,
      energyCost: 240000,
      labourCost: 560000,
      opex: 210000,
      maintenanceCost: 95000,
      workingCapital: 320000,
    },
    circular: {
      revenueDeltaPct: 14,
      materialCostDeltaPct: -18,
      energyCostDeltaPct: 10,
      labourCostDeltaPct: 12,
      opexDeltaPct: 8,
      maintenanceDeltaPct: 12,
      capex: 520000,
      workingCapitalDelta: 120000,
      recurringRevenueSharePct: 22,
      customerRetentionPct: 66,
      residualValue: 60000,
    },
    inputs: mkInputs({
      marketAttractiveness: 60,
      customerDemand: 46,
      revenuePotential: 58,
      marginPotential: 54,
      operationalFeasibility: 44,
      scalability: 48,
      capexRequirement: 520000,
      annualRevenueUplift: 294000,
      annualCostSaving: 194000,
      paybackYears: 5.2,
      commercialRisk: 62,
      resourceExposure: 66,
      supplierConcentration: 55,
      materialDependency: 70,
      importExposure: 58,
      resourcePriceVolatility: 74,
      substitutionOptions: 42,
      recurringRevenueShare: 22,
      customerRetention: 66,
      repairability: 40,
      reuseOpportunity: 62,
      customerEvidence: 38,
      marketValidation: 40,
      commercialTraction: 34,
      unitEconomics: 44,
      managementCapability: 52,
      capitalClarity: 46,
      circularPropositionClarity: 60,
      materialRecoveryPotential: 74,
      lifetimeExtensionPotential: 54,
      circularRevenueModelStrength: 56,
      supplyChainBenefit: 64,
      resourceSecurityBenefit: 70,
      evidenceCoverage: 40,
      evidenceRecency: 44,
      evidenceIndependence: 36,
      evidenceVerification: 34,
    }),
    evidence: [
      {
        type: "Internal estimate",
        description: "Bench trials suggest 55-65% usable fibre yield from returned textiles.",
        source: "R&D notebook",
        confidence: 40,
        linkedArea: "Material recovery",
        status: "Unverified",
        agedMonths: 6,
      },
      {
        type: "Market study",
        description: "Desk research on recycled-content fabric premiums.",
        source: "Trade publication",
        confidence: 42,
        linkedArea: "Market validation",
        status: "Provisional",
        agedMonths: 11,
      },
    ],
    resourceDeps: [
      {
        material: "Virgin wool yarn",
        criticality: "High",
        annualSpend: 720000,
        volatility: "High",
        notes: "Dominant input; highly price-volatile.",
      },
      {
        material: "Dyes & finishing chemicals",
        criticality: "Medium",
        annualSpend: 180000,
        volatility: "Medium",
        notes: "Some imported.",
      },
    ],
    supplierRisks: [
      {
        supplier: "Highland Wool Merchants",
        category: "Yarn",
        shareOfSupplyPct: 58,
        region: "UK",
        riskLevel: "High",
      },
      {
        supplier: "Continental Dyes",
        category: "Chemicals",
        shareOfSupplyPct: 46,
        region: "EU",
        riskLevel: "Medium",
      },
    ],
  },
  {
    id: "clyde-precision-manufacturing",
    name: "Clyde Precision Manufacturing",
    sector: "Manufacturing",
    companySize: "Medium (50-249)",
    region: "Glasgow",
    description: "Precision engineering firm making components and sub-assemblies for industrial OEMs.",
    currentOperatingModel: "Machines new components from bar and casting stock to order.",
    currentRevenueModel: "Build-to-print component supply contracts.",
    productsServices: "Machined metal components, sub-assemblies and spares.",
    customerModel: "B2B — industrial OEMs and tier-one suppliers.",
    commercialPressures: "Energy and alloy costs; OEMs seeking remanufactured spares to cut cost and lead time.",
    stage: "In Review",
    circularModels: ["Remanufacturing", "Take-back"],
    opportunitySummary:
      "Add a remanufacturing cell recovering and re-machining worn components returned by OEMs, sold as certified reman spares.",
    commercialRationale:
      "Remanufacturing carries strong margins and locks in OEM relationships; capital for inspection and re-machining equipment is significant but well understood.",
    baseline: {
      revenue: 7400000,
      materialCost: 2900000,
      energyCost: 540000,
      labourCost: 2200000,
      opex: 720000,
      maintenanceCost: 340000,
      workingCapital: 980000,
    },
    circular: {
      revenueDeltaPct: 13,
      materialCostDeltaPct: -16,
      energyCostDeltaPct: 6,
      labourCostDeltaPct: 8,
      opexDeltaPct: 5,
      maintenanceDeltaPct: 10,
      capex: 1250000,
      workingCapitalDelta: 180000,
      recurringRevenueSharePct: 38,
      customerRetentionPct: 84,
      residualValue: 320000,
    },
    inputs: mkInputs({
      marketAttractiveness: 66,
      customerDemand: 68,
      revenuePotential: 66,
      marginPotential: 76,
      operationalFeasibility: 68,
      scalability: 62,
      capexRequirement: 1250000,
      annualRevenueUplift: 962000,
      annualCostSaving: 320000,
      paybackYears: 3.2,
      commercialRisk: 42,
      resourceExposure: 52,
      supplierConcentration: 48,
      materialDependency: 60,
      importExposure: 46,
      resourcePriceVolatility: 56,
      recurringRevenueShare: 38,
      customerRetention: 84,
      customerEvidence: 66,
      marketValidation: 62,
      commercialTraction: 60,
      unitEconomics: 70,
      managementCapability: 70,
      operatingCapability: 72,
      capitalClarity: 68,
      riskUnderstanding: 64,
      circularPropositionClarity: 70,
      dataQuality: 64,
      materialRecoveryPotential: 72,
      lifetimeExtensionPotential: 70,
      circularRevenueModelStrength: 68,
      supplyChainBenefit: 66,
      resourceSecurityBenefit: 62,
      evidenceCoverage: 64,
      evidenceRecency: 66,
      evidenceIndependence: 58,
      evidenceVerification: 62,
    }),
    evidence: [
      {
        type: "Customer interview",
        description: "Two OEMs committed to trial reman spares programme.",
        source: "Key accounts",
        confidence: 70,
        linkedArea: "Customer demand",
        status: "Verified",
        agedMonths: 3,
      },
      {
        type: "Financial record",
        description: "Machining margin data supports reman contribution model.",
        source: "Cost accounting",
        confidence: 76,
        linkedArea: "Unit economics",
        status: "Verified",
        agedMonths: 5,
      },
      {
        type: "External benchmark",
        description: "Remanufacturing cost-savings benchmarks for industrial spares.",
        source: "Sector study",
        confidence: 60,
        linkedArea: "Market validation",
        status: "Provisional",
        agedMonths: 9,
      },
    ],
    resourceDeps: [
      {
        material: "Alloy bar & castings",
        criticality: "High",
        annualSpend: 1600000,
        volatility: "Medium",
        notes: "Primary machining stock.",
      },
      {
        material: "Cutting tools & coolant",
        criticality: "Medium",
        annualSpend: 300000,
        volatility: "Low",
        notes: "Consumables.",
      },
    ],
    supplierRisks: [
      {
        supplier: "Caledonian Alloys",
        category: "Metal stock",
        shareOfSupplyPct: 52,
        region: "UK",
        riskLevel: "Medium",
      },
      {
        supplier: "Precision Tooling Ltd",
        category: "Tooling",
        shareOfSupplyPct: 34,
        region: "EU",
        riskLevel: "Low",
      },
    ],
  },
  {
    id: "tay-valley-food-co",
    name: "Tay Valley Food Co",
    sector: "Food & Drink",
    companySize: "Small (10-49)",
    region: "Perth",
    description: "Producer of preserves, sauces and ready meals using local produce.",
    currentOperatingModel: "Processes fresh produce into ambient and chilled products; side-streams discarded.",
    currentRevenueModel: "Wholesale and own-brand retail sales.",
    productsServices: "Preserves, sauces, soups and ready meals.",
    customerModel: "B2B wholesale and B2C via retailers and farm shops.",
    commercialPressures: "Produce waste and disposal cost; retailer demand for provenance and low-waste credentials.",
    stage: "In Review",
    circularModels: ["Waste-to-value"],
    opportunitySummary:
      "Convert fruit and vegetable side-streams into a new range of stocks, powders and pet-food ingredients.",
    commercialRationale:
      "Waste-to-value turns a disposal cost into a low-capital revenue stream with good demand; margins are moderate and scale is limited by side-stream volume.",
    baseline: {
      revenue: 1650000,
      materialCost: 720000,
      energyCost: 150000,
      labourCost: 430000,
      opex: 160000,
      maintenanceCost: 60000,
      workingCapital: 210000,
    },
    circular: {
      revenueDeltaPct: 18,
      materialCostDeltaPct: -6,
      energyCostDeltaPct: 8,
      labourCostDeltaPct: 10,
      opexDeltaPct: 6,
      maintenanceDeltaPct: 8,
      capex: 180000,
      workingCapitalDelta: 45000,
      recurringRevenueSharePct: 30,
      customerRetentionPct: 74,
      residualValue: 20000,
    },
    inputs: mkInputs({
      marketAttractiveness: 62,
      customerDemand: 66,
      revenuePotential: 58,
      marginPotential: 56,
      operationalFeasibility: 64,
      scalability: 46,
      capexRequirement: 180000,
      annualRevenueUplift: 297000,
      annualCostSaving: 64000,
      paybackYears: 1.8,
      commercialRisk: 44,
      resourceExposure: 40,
      supplierConcentration: 40,
      materialDependency: 48,
      resourcePriceVolatility: 50,
      recurringRevenueShare: 30,
      customerRetention: 74,
      reuseOpportunity: 66,
      customerEvidence: 60,
      marketValidation: 56,
      commercialTraction: 52,
      unitEconomics: 56,
      managementCapability: 58,
      capitalClarity: 60,
      circularPropositionClarity: 66,
      materialRecoveryPotential: 68,
      lifetimeExtensionPotential: 44,
      circularRevenueModelStrength: 60,
      supplyChainBenefit: 54,
      resourceSecurityBenefit: 52,
      evidenceCoverage: 56,
      evidenceRecency: 60,
      evidenceIndependence: 50,
      evidenceVerification: 54,
    }),
    evidence: [
      {
        type: "Pilot data",
        description: "Vegetable-stock trial sold out at two farm shops.",
        source: "Retail pilot",
        confidence: 64,
        linkedArea: "Customer demand",
        status: "Verified",
        agedMonths: 2,
      },
      {
        type: "Financial record",
        description: "Current disposal cost of side-streams quantified.",
        source: "Waste invoices",
        confidence: 70,
        linkedArea: "Cost saving",
        status: "Verified",
        agedMonths: 4,
      },
    ],
    resourceDeps: [
      {
        material: "Fresh produce",
        criticality: "High",
        annualSpend: 560000,
        volatility: "Medium",
        notes: "Seasonal; local sourcing.",
      },
      {
        material: "Glass & packaging",
        criticality: "Medium",
        annualSpend: 140000,
        volatility: "Medium",
        notes: "",
      },
    ],
    supplierRisks: [
      {
        supplier: "Perthshire Growers Co-op",
        category: "Produce",
        shareOfSupplyPct: 48,
        region: "UK",
        riskLevel: "Medium",
      },
      {
        supplier: "Scotia Glass",
        category: "Packaging",
        shareOfSupplyPct: 40,
        region: "UK",
        riskLevel: "Low",
      },
    ],
  },
  {
    id: "granite-city-electronics",
    name: "Granite City Electronics",
    sector: "Electronics",
    companySize: "Small (10-49)",
    region: "Aberdeen",
    description: "Distributor and servicer of industrial control and instrumentation electronics.",
    currentOperatingModel: "Sells new units and offers limited warranty repair.",
    currentRevenueModel: "Hardware sales with a small service revenue.",
    productsServices: "Control units, sensors and instrumentation for energy and industrial clients.",
    customerModel: "B2B — energy, utilities and industrial maintenance teams.",
    commercialPressures: "Component import exposure and lead times; clients seeking repair over replacement.",
    stage: "Draft",
    circularModels: ["Repair", "Take-back", "Refurbishment"],
    opportunitySummary:
      "Build a repair and refurbishment service recovering, testing and re-certifying returned units for resale and warranty pools.",
    commercialRationale:
      "Repair improves resource security against volatile component imports and adds service margin; the challenge is import exposure and building a repair workforce.",
    baseline: {
      revenue: 2800000,
      materialCost: 1500000,
      energyCost: 110000,
      labourCost: 620000,
      opex: 240000,
      maintenanceCost: 70000,
      workingCapital: 360000,
    },
    circular: {
      revenueDeltaPct: 11,
      materialCostDeltaPct: -12,
      energyCostDeltaPct: 3,
      labourCostDeltaPct: 14,
      opexDeltaPct: 5,
      maintenanceDeltaPct: 6,
      capex: 240000,
      workingCapitalDelta: 60000,
      recurringRevenueSharePct: 34,
      customerRetentionPct: 76,
      residualValue: 70000,
    },
    inputs: mkInputs({
      marketAttractiveness: 58,
      customerDemand: 60,
      revenuePotential: 56,
      marginPotential: 62,
      operationalFeasibility: 54,
      scalability: 52,
      capexRequirement: 240000,
      annualRevenueUplift: 308000,
      annualCostSaving: 180000,
      paybackYears: 2.9,
      commercialRisk: 50,
      resourceExposure: 64,
      supplierConcentration: 50,
      materialDependency: 62,
      importExposure: 78,
      resourcePriceVolatility: 60,
      substitutionOptions: 44,
      recurringRevenueShare: 34,
      customerRetention: 76,
      repairability: 80,
      reuseOpportunity: 70,
      customerEvidence: 50,
      marketValidation: 48,
      commercialTraction: 46,
      unitEconomics: 54,
      managementCapability: 56,
      capitalClarity: 52,
      circularPropositionClarity: 64,
      materialRecoveryPotential: 64,
      lifetimeExtensionPotential: 74,
      circularRevenueModelStrength: 58,
      supplyChainBenefit: 68,
      resourceSecurityBenefit: 74,
      evidenceCoverage: 48,
      evidenceRecency: 52,
      evidenceIndependence: 44,
      evidenceVerification: 46,
    }),
    evidence: [
      {
        type: "Customer interview",
        description: "Maintenance teams open to certified refurbished units for non-critical assets.",
        source: "Field sales",
        confidence: 52,
        linkedArea: "Customer demand",
        status: "Provisional",
        agedMonths: 5,
      },
      {
        type: "Internal estimate",
        description: "Repair labour times and pass rates estimated from warranty data.",
        source: "Service desk",
        confidence: 48,
        linkedArea: "Operational feasibility",
        status: "Unverified",
        agedMonths: 6,
      },
    ],
    resourceDeps: [
      {
        material: "Semiconductors & modules",
        criticality: "High",
        annualSpend: 900000,
        volatility: "High",
        notes: "Import-exposed; long lead times.",
      },
      {
        material: "Enclosures & connectors",
        criticality: "Medium",
        annualSpend: 260000,
        volatility: "Medium",
        notes: "",
      },
    ],
    supplierRisks: [
      {
        supplier: "Asia-Pacific Components",
        category: "Semiconductors",
        shareOfSupplyPct: 70,
        region: "Asia",
        riskLevel: "High",
      },
      {
        supplier: "North Sea Electrical",
        category: "Enclosures",
        shareOfSupplyPct: 36,
        region: "UK",
        riskLevel: "Low",
      },
    ],
  },
  {
    id: "lothian-packaging",
    name: "Lothian Packaging",
    sector: "Packaging",
    companySize: "Medium (50-249)",
    region: "Livingston",
    description: "Manufacturer of transit and retail packaging for food and consumer-goods clients.",
    currentOperatingModel: "Produces single-use fibre and plastic packaging at volume.",
    currentRevenueModel: "High-volume, low-margin unit sales.",
    productsServices: "Corrugated cases, trays and moulded-fibre packaging.",
    customerModel: "B2B — FMCG and food manufacturers.",
    commercialPressures: "Thin margins, plastic-tax exposure and customer demand for recycled-content and closed-loop schemes.",
    stage: "Draft",
    circularModels: ["Closed-loop material recovery", "Take-back"],
    opportunitySummary:
      "Operate a closed-loop scheme recovering used packaging from large clients and reprocessing it into new recycled-content packaging.",
    commercialRationale:
      "Closed-loop recovery hedges plastic-tax and virgin-fibre exposure, but the model is capital-heavy and margins remain thin, weakening the investment case.",
    baseline: {
      revenue: 6100000,
      materialCost: 3400000,
      energyCost: 560000,
      labourCost: 1400000,
      opex: 480000,
      maintenanceCost: 260000,
      workingCapital: 760000,
    },
    circular: {
      revenueDeltaPct: 9,
      materialCostDeltaPct: -13,
      energyCostDeltaPct: 12,
      labourCostDeltaPct: 8,
      opexDeltaPct: 7,
      maintenanceDeltaPct: 16,
      capex: 1650000,
      workingCapitalDelta: 210000,
      recurringRevenueSharePct: 40,
      customerRetentionPct: 80,
      residualValue: 240000,
    },
    inputs: mkInputs({
      marketAttractiveness: 56,
      customerDemand: 58,
      revenuePotential: 52,
      marginPotential: 40,
      operationalFeasibility: 52,
      scalability: 58,
      capexRequirement: 1650000,
      annualRevenueUplift: 549000,
      annualCostSaving: 300000,
      paybackYears: 5.8,
      commercialRisk: 58,
      resourceExposure: 60,
      supplierConcentration: 46,
      materialDependency: 64,
      importExposure: 44,
      resourcePriceVolatility: 62,
      recurringRevenueShare: 40,
      customerRetention: 80,
      customerEvidence: 54,
      marketValidation: 52,
      commercialTraction: 44,
      unitEconomics: 42,
      managementCapability: 58,
      capitalClarity: 48,
      riskUnderstanding: 50,
      circularPropositionClarity: 60,
      materialRecoveryPotential: 72,
      lifetimeExtensionPotential: 40,
      circularRevenueModelStrength: 54,
      supplyChainBenefit: 64,
      resourceSecurityBenefit: 62,
      evidenceCoverage: 50,
      evidenceRecency: 54,
      evidenceIndependence: 46,
      evidenceVerification: 48,
    }),
    evidence: [
      {
        type: "Customer interview",
        description: "Three FMCG clients keen on closed-loop but price-sensitive.",
        source: "Account management",
        confidence: 54,
        linkedArea: "Customer demand",
        status: "Provisional",
        agedMonths: 4,
      },
      {
        type: "External benchmark",
        description: "Recycled-content packaging cost benchmarks.",
        source: "Industry data",
        confidence: 56,
        linkedArea: "Unit economics",
        status: "Provisional",
        agedMonths: 7,
      },
    ],
    resourceDeps: [
      {
        material: "Virgin fibre & board",
        criticality: "High",
        annualSpend: 1900000,
        volatility: "Medium",
        notes: "",
      },
      {
        material: "Polymer resin",
        criticality: "High",
        annualSpend: 900000,
        volatility: "High",
        notes: "Plastic-tax exposed.",
      },
    ],
    supplierRisks: [
      {
        supplier: "UK Fibre Mills",
        category: "Board",
        shareOfSupplyPct: 50,
        region: "UK",
        riskLevel: "Medium",
      },
      {
        supplier: "Euro Polymers",
        category: "Resin",
        shareOfSupplyPct: 55,
        region: "EU",
        riskLevel: "High",
      },
    ],
  },
  {
    id: "highland-timber-joinery",
    name: "Highland Timber & Joinery",
    sector: "Construction",
    companySize: "Small (10-49)",
    region: "Fort William",
    description: "Joinery and timber-frame manufacturer for housing and commercial projects.",
    currentOperatingModel: "Cuts new timber to order; off-cuts and reclaimed timber largely unused.",
    currentRevenueModel: "Project-based joinery and frame contracts.",
    productsServices: "Timber frames, staircases, doors and bespoke joinery.",
    customerModel: "B2B — housebuilders, contractors and architects.",
    commercialPressures: "Timber price swings and waste; interest in reclaimed and lifetime-extended timber products.",
    stage: "Draft",
    circularModels: ["Reuse", "Lifetime extension"],
    opportunitySummary:
      "Set up a reclaimed-timber line recovering off-cuts and deconstruction timber into graded reuse products and refurbished joinery.",
    commercialRationale:
      "Strong material savings and provenance appeal, but weak commercial evidence and low management bandwidth make it early-stage for investment.",
    baseline: {
      revenue: 1900000,
      materialCost: 940000,
      energyCost: 120000,
      labourCost: 560000,
      opex: 150000,
      maintenanceCost: 55000,
      workingCapital: 240000,
    },
    circular: {
      revenueDeltaPct: 10,
      materialCostDeltaPct: -20,
      energyCostDeltaPct: 5,
      labourCostDeltaPct: 12,
      opexDeltaPct: 6,
      maintenanceDeltaPct: 6,
      capex: 150000,
      workingCapitalDelta: 40000,
      recurringRevenueSharePct: 16,
      customerRetentionPct: 64,
      residualValue: 30000,
    },
    inputs: mkInputs({
      marketAttractiveness: 54,
      customerDemand: 52,
      revenuePotential: 50,
      marginPotential: 58,
      operationalFeasibility: 50,
      scalability: 42,
      capexRequirement: 150000,
      annualRevenueUplift: 190000,
      annualCostSaving: 188000,
      paybackYears: 2.6,
      commercialRisk: 52,
      resourceExposure: 54,
      supplierConcentration: 48,
      materialDependency: 62,
      resourcePriceVolatility: 66,
      recurringRevenueShare: 16,
      customerRetention: 64,
      repairability: 68,
      reuseOpportunity: 82,
      revenueDiversity: 44,
      customerEvidence: 40,
      marketValidation: 42,
      commercialTraction: 36,
      unitEconomics: 46,
      managementCapability: 46,
      operatingCapability: 50,
      capitalClarity: 44,
      circularPropositionClarity: 58,
      materialRecoveryPotential: 76,
      lifetimeExtensionPotential: 78,
      circularRevenueModelStrength: 50,
      supplyChainBenefit: 60,
      resourceSecurityBenefit: 64,
      evidenceCoverage: 40,
      evidenceRecency: 46,
      evidenceIndependence: 38,
      evidenceVerification: 40,
    }),
    evidence: [
      {
        type: "Internal estimate",
        description: "Off-cut volumes and reclaimable timber estimated from production logs.",
        source: "Workshop records",
        confidence: 44,
        linkedArea: "Material recovery",
        status: "Unverified",
        agedMonths: 5,
      },
      {
        type: "Customer interview",
        description: "Two architects interested in reclaimed-timber specification.",
        source: "Business development",
        confidence: 42,
        linkedArea: "Customer demand",
        status: "Provisional",
        agedMonths: 6,
      },
    ],
    resourceDeps: [
      {
        material: "Structural timber",
        criticality: "High",
        annualSpend: 720000,
        volatility: "High",
        notes: "Price-volatile softwood.",
      },
      {
        material: "Fixings & finishes",
        criticality: "Low",
        annualSpend: 120000,
        volatility: "Low",
        notes: "",
      },
    ],
    supplierRisks: [
      {
        supplier: "Caledonian Timber",
        category: "Timber",
        shareOfSupplyPct: 60,
        region: "UK",
        riskLevel: "High",
      },
      {
        supplier: "West Coast Fixings",
        category: "Fixings",
        shareOfSupplyPct: 30,
        region: "UK",
        riskLevel: "Low",
      },
    ],
  },
  {
    id: "aberdeen-marine-rentals",
    name: "Aberdeen Marine Rentals",
    sector: "Industrial Services",
    companySize: "Medium (50-249)",
    region: "Aberdeen",
    description: "Provider of subsea and marine support equipment to the energy and offshore-wind sectors.",
    currentOperatingModel: "Owns and hires a fleet of marine and subsea equipment.",
    currentRevenueModel: "Day-rate hire and mobilisation charges.",
    productsServices: "ROV support units, tooling, containers and marine equipment.",
    customerModel: "B2B — offshore energy operators and marine contractors.",
    commercialPressures: "Cyclical demand and high asset cost; clients want lifecycle and uptime guarantees.",
    stage: "In Review",
    circularModels: ["Leasing", "Lifetime extension"],
    opportunitySummary:
      "Extend the leasing model with lifecycle management and refurbishment to keep high-value assets in service longer at guaranteed availability.",
    commercialRationale:
      "Leasing plus lifetime extension delivers strong recurring revenue and resilience; sector cyclicality is the main risk.",
    baseline: {
      revenue: 8600000,
      materialCost: 2600000,
      energyCost: 420000,
      labourCost: 2900000,
      opex: 1100000,
      maintenanceCost: 720000,
      workingCapital: 1300000,
    },
    circular: {
      revenueDeltaPct: 10,
      materialCostDeltaPct: -10,
      energyCostDeltaPct: 4,
      labourCostDeltaPct: 6,
      opexDeltaPct: 5,
      maintenanceDeltaPct: 12,
      capex: 1400000,
      workingCapitalDelta: 220000,
      recurringRevenueSharePct: 70,
      customerRetentionPct: 82,
      residualValue: 780000,
    },
    inputs: mkInputs({
      marketAttractiveness: 60,
      customerDemand: 62,
      revenuePotential: 64,
      marginPotential: 62,
      operationalFeasibility: 66,
      scalability: 60,
      capexRequirement: 1400000,
      annualRevenueUplift: 860000,
      annualCostSaving: 300000,
      paybackYears: 3.9,
      commercialRisk: 54,
      resourceExposure: 44,
      supplierConcentration: 40,
      materialDependency: 42,
      resourcePriceVolatility: 46,
      substitutionOptions: 58,
      recurringRevenueShare: 70,
      customerRetention: 82,
      revenueDiversity: 62,
      operationalFlexibility: 66,
      customerEvidence: 64,
      marketValidation: 60,
      commercialTraction: 62,
      unitEconomics: 66,
      managementCapability: 70,
      operatingCapability: 72,
      capitalClarity: 64,
      riskUnderstanding: 62,
      circularPropositionClarity: 68,
      dataQuality: 62,
      materialRecoveryPotential: 60,
      lifetimeExtensionPotential: 78,
      circularRevenueModelStrength: 74,
      supplyChainBenefit: 62,
      resourceSecurityBenefit: 60,
      evidenceCoverage: 62,
      evidenceRecency: 64,
      evidenceIndependence: 56,
      evidenceVerification: 60,
    }),
    evidence: [
      {
        type: "Financial record",
        description: "Fleet lifecycle costs and day-rate history support extension case.",
        source: "Asset register",
        confidence: 74,
        linkedArea: "Unit economics",
        status: "Verified",
        agedMonths: 6,
      },
      {
        type: "Customer interview",
        description: "Operators value guaranteed availability contracts.",
        source: "Commercial team",
        confidence: 64,
        linkedArea: "Customer demand",
        status: "Provisional",
        agedMonths: 4,
      },
    ],
    resourceDeps: [
      {
        material: "Steel & subsea components",
        criticality: "Medium",
        annualSpend: 1300000,
        volatility: "Medium",
        notes: "",
      },
      {
        material: "Hydraulic & electronic spares",
        criticality: "Medium",
        annualSpend: 620000,
        volatility: "Medium",
        notes: "",
      },
    ],
    supplierRisks: [
      {
        supplier: "North Sea Fabrication",
        category: "Fabrication",
        shareOfSupplyPct: 42,
        region: "UK",
        riskLevel: "Medium",
      },
      {
        supplier: "Subsea Systems Intl",
        category: "Components",
        shareOfSupplyPct: 38,
        region: "EU",
        riskLevel: "Medium",
      },
    ],
  },
  {
    id: "borders-woollen-mill",
    name: "Borders Woollen Mill",
    sector: "Textiles",
    companySize: "Micro (1-9)",
    region: "Galashiels",
    description: "Heritage woollen mill producing premium knitwear and accessories.",
    currentOperatingModel: "Knits premium garments from wool yarn; take-back and repair informal.",
    currentRevenueModel: "Direct-to-consumer and boutique wholesale.",
    productsServices: "Knitwear, scarves and accessories.",
    customerModel: "B2C premium and boutique B2B.",
    commercialPressures: "Premium positioning under cost pressure; customers value repairability and longevity.",
    stage: "In Review",
    circularModels: ["Repair", "Reuse", "Lifetime extension"],
    opportunitySummary:
      "Formalise a repair-and-renew service and a certified pre-loved resale channel to extend garment life and deepen brand loyalty.",
    commercialRationale:
      "Low-capital, brand-aligned and margin-accretive with strong retention; scale is limited by the niche premium market.",
    baseline: {
      revenue: 720000,
      materialCost: 300000,
      energyCost: 45000,
      labourCost: 210000,
      opex: 70000,
      maintenanceCost: 20000,
      workingCapital: 110000,
    },
    circular: {
      revenueDeltaPct: 15,
      materialCostDeltaPct: -8,
      energyCostDeltaPct: 3,
      labourCostDeltaPct: 10,
      opexDeltaPct: 5,
      maintenanceDeltaPct: 4,
      capex: 45000,
      workingCapitalDelta: 12000,
      recurringRevenueSharePct: 26,
      customerRetentionPct: 84,
      residualValue: 8000,
    },
    inputs: mkInputs({
      marketAttractiveness: 58,
      customerDemand: 64,
      revenuePotential: 52,
      marginPotential: 66,
      operationalFeasibility: 66,
      scalability: 40,
      capexRequirement: 45000,
      annualRevenueUplift: 108000,
      annualCostSaving: 30000,
      paybackYears: 1.3,
      commercialRisk: 40,
      resourceExposure: 42,
      supplierConcentration: 44,
      materialDependency: 52,
      resourcePriceVolatility: 58,
      recurringRevenueShare: 26,
      customerRetention: 84,
      repairability: 78,
      reuseOpportunity: 74,
      revenueDiversity: 48,
      customerEvidence: 62,
      marketValidation: 54,
      commercialTraction: 56,
      unitEconomics: 60,
      managementCapability: 56,
      capitalClarity: 62,
      circularPropositionClarity: 74,
      materialRecoveryPotential: 58,
      lifetimeExtensionPotential: 80,
      circularRevenueModelStrength: 62,
      supplyChainBenefit: 52,
      resourceSecurityBenefit: 54,
      evidenceCoverage: 56,
      evidenceRecency: 62,
      evidenceIndependence: 48,
      evidenceVerification: 56,
    }),
    evidence: [
      {
        type: "Customer interview",
        description: "Loyal customers value repair service; willingness to pay confirmed.",
        source: "Customer survey",
        confidence: 62,
        linkedArea: "Customer demand",
        status: "Verified",
        agedMonths: 3,
      },
      {
        type: "Pilot data",
        description: "Repair service pilot achieved strong repeat-purchase uplift.",
        source: "Retail pilot",
        confidence: 58,
        linkedArea: "Customer retention",
        status: "Provisional",
        agedMonths: 4,
      },
    ],
    resourceDeps: [
      {
        material: "Wool yarn",
        criticality: "High",
        annualSpend: 220000,
        volatility: "High",
        notes: "",
      },
      {
        material: "Trims & packaging",
        criticality: "Low",
        annualSpend: 40000,
        volatility: "Low",
        notes: "",
      },
    ],
    supplierRisks: [
      {
        supplier: "Border Spinners",
        category: "Yarn",
        shareOfSupplyPct: 50,
        region: "UK",
        riskLevel: "Medium",
      },
      {
        supplier: "Tweed Trims",
        category: "Trims",
        shareOfSupplyPct: 34,
        region: "UK",
        riskLevel: "Low",
      },
    ],
  },
  {
    id: "dundee-appliance-loop",
    name: "Dundee Appliance Loop",
    sector: "Consumer Goods",
    companySize: "Small (10-49)",
    region: "Dundee",
    description: "Retailer and refurbisher of domestic appliances with a growing subscription offer.",
    currentOperatingModel: "Retails new and graded appliances; nascent refurbishment.",
    currentRevenueModel: "Retail sales plus a small subscription pilot.",
    productsServices: "Washing machines, fridges and small domestic appliances.",
    customerModel: "B2C and social-housing B2B.",
    commercialPressures: "Cost-of-living pressure on customers; demand for affordable, guaranteed appliances.",
    stage: "Investment Ready",
    circularModels: ["Subscription", "Refurbishment"],
    opportunitySummary:
      "Scale an appliance subscription with refurbishment and take-back: customers subscribe to guaranteed appliances, returned units are refurbished and re-subscribed.",
    commercialRationale:
      "Subscription plus refurbishment builds strong recurring revenue and retention with moderate capital; social-housing demand underpins the case.",
    baseline: {
      revenue: 2400000,
      materialCost: 1300000,
      energyCost: 90000,
      labourCost: 520000,
      opex: 220000,
      maintenanceCost: 80000,
      workingCapital: 300000,
    },
    circular: {
      revenueDeltaPct: 17,
      materialCostDeltaPct: -14,
      energyCostDeltaPct: 4,
      labourCostDeltaPct: 12,
      opexDeltaPct: 6,
      maintenanceDeltaPct: 12,
      capex: 420000,
      workingCapitalDelta: 130000,
      recurringRevenueSharePct: 58,
      customerRetentionPct: 82,
      residualValue: 150000,
    },
    inputs: mkInputs({
      marketAttractiveness: 66,
      customerDemand: 72,
      revenuePotential: 68,
      marginPotential: 64,
      operationalFeasibility: 64,
      scalability: 66,
      capexRequirement: 420000,
      annualRevenueUplift: 408000,
      annualCostSaving: 182000,
      paybackYears: 2.7,
      commercialRisk: 44,
      resourceExposure: 46,
      supplierConcentration: 46,
      materialDependency: 54,
      importExposure: 52,
      resourcePriceVolatility: 48,
      recurringRevenueShare: 58,
      customerRetention: 82,
      revenueDiversity: 60,
      repairability: 72,
      reuseOpportunity: 74,
      customerEvidence: 68,
      marketValidation: 64,
      commercialTraction: 66,
      unitEconomics: 66,
      managementCapability: 66,
      operatingCapability: 64,
      capitalClarity: 66,
      riskUnderstanding: 62,
      circularPropositionClarity: 72,
      dataQuality: 62,
      materialRecoveryPotential: 66,
      lifetimeExtensionPotential: 74,
      circularRevenueModelStrength: 76,
      supplyChainBenefit: 58,
      resourceSecurityBenefit: 56,
      evidenceCoverage: 64,
      evidenceRecency: 66,
      evidenceIndependence: 58,
      evidenceVerification: 62,
    }),
    evidence: [
      {
        type: "Financial record",
        description: "Subscription pilot shows 82% 12-month retention.",
        source: "Subscription ledger",
        confidence: 76,
        linkedArea: "Customer retention",
        status: "Verified",
        agedMonths: 3,
      },
      {
        type: "Customer interview",
        description: "Two housing associations committed to a subscription framework.",
        source: "B2B pipeline",
        confidence: 70,
        linkedArea: "Customer demand",
        status: "Verified",
        agedMonths: 2,
      },
      {
        type: "External benchmark",
        description: "Appliance refurbishment yield benchmarks.",
        source: "Sector data",
        confidence: 60,
        linkedArea: "Material recovery",
        status: "Provisional",
        agedMonths: 8,
      },
    ],
    resourceDeps: [
      {
        material: "Appliance stock",
        criticality: "High",
        annualSpend: 980000,
        volatility: "Medium",
        notes: "New and graded units.",
      },
      {
        material: "Spare parts",
        criticality: "Medium",
        annualSpend: 220000,
        volatility: "Medium",
        notes: "Refurbishment inputs.",
      },
    ],
    supplierRisks: [
      {
        supplier: "National Appliance Wholesale",
        category: "Appliances",
        shareOfSupplyPct: 48,
        region: "UK",
        riskLevel: "Medium",
      },
      {
        supplier: "Parts Direct",
        category: "Spares",
        shareOfSupplyPct: 40,
        region: "EU",
        riskLevel: "Low",
      },
    ],
  },
  {
    id: "stirling-toolshare",
    name: "Stirling Toolshare",
    sector: "Equipment Rental",
    companySize: "Micro (1-9)",
    region: "Stirling",
    description: "Community and trade tool-sharing platform with staffed collection points.",
    currentOperatingModel: "Operates a small shared tool library with pay-per-use access.",
    currentRevenueModel: "Membership and pay-per-use hire.",
    productsServices: "Power tools, garden and DIY equipment for shared use.",
    customerModel: "B2C members and small trade users.",
    commercialPressures: "Low margins and utilisation risk; growth needs density and better asset management.",
    stage: "Draft",
    circularModels: ["Sharing", "Repair"],
    opportunitySummary:
      "Grow the sharing platform with better asset tracking, repair and route density to raise utilisation and membership revenue.",
    commercialRationale:
      "Asset-light and low-capital with genuine recurring revenue potential, but weak current margins and unproven unit economics make it early-stage.",
    baseline: {
      revenue: 320000,
      materialCost: 60000,
      energyCost: 18000,
      labourCost: 150000,
      opex: 70000,
      maintenanceCost: 40000,
      workingCapital: 45000,
    },
    circular: {
      revenueDeltaPct: 22,
      materialCostDeltaPct: -4,
      energyCostDeltaPct: 4,
      labourCostDeltaPct: 14,
      opexDeltaPct: 8,
      maintenanceDeltaPct: 10,
      capex: 60000,
      workingCapitalDelta: 15000,
      recurringRevenueSharePct: 62,
      customerRetentionPct: 70,
      residualValue: 12000,
    },
    inputs: mkInputs({
      marketAttractiveness: 52,
      customerDemand: 56,
      revenuePotential: 48,
      marginPotential: 38,
      operationalFeasibility: 50,
      scalability: 58,
      capexRequirement: 60000,
      annualRevenueUplift: 70000,
      annualCostSaving: 12000,
      paybackYears: 3.4,
      commercialRisk: 56,
      resourceExposure: 38,
      supplierConcentration: 36,
      materialDependency: 34,
      resourcePriceVolatility: 40,
      substitutionOptions: 56,
      recurringRevenueShare: 62,
      customerRetention: 70,
      revenueDiversity: 46,
      repairability: 72,
      reuseOpportunity: 76,
      operationalFlexibility: 58,
      customerEvidence: 44,
      marketValidation: 44,
      commercialTraction: 40,
      unitEconomics: 40,
      managementCapability: 48,
      operatingCapability: 48,
      capitalClarity: 50,
      circularPropositionClarity: 64,
      materialRecoveryPotential: 52,
      lifetimeExtensionPotential: 70,
      circularRevenueModelStrength: 58,
      supplyChainBenefit: 46,
      resourceSecurityBenefit: 48,
      evidenceCoverage: 42,
      evidenceRecency: 50,
      evidenceIndependence: 40,
      evidenceVerification: 42,
    }),
    evidence: [
      {
        type: "Internal estimate",
        description: "Utilisation and churn estimated from platform logs.",
        source: "Platform analytics",
        confidence: 46,
        linkedArea: "Unit economics",
        status: "Unverified",
        agedMonths: 3,
      },
      {
        type: "Customer interview",
        description: "Members value convenience but are price-sensitive.",
        source: "Member survey",
        confidence: 44,
        linkedArea: "Customer demand",
        status: "Provisional",
        agedMonths: 5,
      },
    ],
    resourceDeps: [
      {
        material: "Tools & equipment",
        criticality: "Medium",
        annualSpend: 50000,
        volatility: "Low",
        notes: "Shared assets.",
      },
      {
        material: "Consumables & spares",
        criticality: "Low",
        annualSpend: 18000,
        volatility: "Low",
        notes: "",
      },
    ],
    supplierRisks: [
      {
        supplier: "Trade Tool Supply",
        category: "Tools",
        shareOfSupplyPct: 42,
        region: "UK",
        riskLevel: "Low",
      },
      {
        supplier: "DIY Wholesale",
        category: "Consumables",
        shareOfSupplyPct: 28,
        region: "UK",
        riskLevel: "Low",
      },
    ],
  },
];

/** Programme-level synthetic reference rows (aggregate, anonymised). */
export const PROGRAMME_INSIGHTS: {
  metric: string;
  category: string;
  value: number;
  unit: string;
  note: string;
}[] = [
  { metric: "Businesses engaged", category: "Reach", value: 12, unit: "count", note: "Synthetic cohort in this demonstrator." },
  { metric: "Median commercial viability", category: "Commercial", value: 58, unit: "score", note: "Across the synthetic cohort." },
  { metric: "Median investor readiness", category: "Investment", value: 54, unit: "score", note: "Several businesses need evidence before funding." },
  { metric: "Total capital requirement", category: "Capital", value: 8555000, unit: "GBP", note: "Sum of prototype capex across cohort." },
  { metric: "Projected annual commercial opportunity", category: "Commercial", value: 5980000, unit: "GBP", note: "Sum of circular-case EBITDA uplift vs baseline." },
  { metric: "Businesses needing adviser support", category: "Support", value: 5, unit: "count", note: "Viability strong but evidence confidence low." },
];
