import type { Connector, GraphEdge, GraphNode } from "./types";

/**
 * The CIRCA connector registry. Statuses are truthful:
 * - DEMO DATA: wired into the opportunity engine, running on the deterministic
 *   demonstrator dataset; architecture is ready for live credentials.
 * - READY TO CONFIGURE: typed adapter in place, needs credentials/consent.
 * - API ACCESS REQUIRED / Partnership connector: needs a commercial or
 *   partnership agreement before any connection.
 */
export const CONNECTORS: Connector[] = [
  // ── ERP ───────────────────────────────────────────────────────────────────
  {
    id: "sap-s4hana",
    name: "SAP S/4HANA",
    provider: "SAP",
    category: "ERP",
    status: "DEMO DATA",
    direction: "inbound",
    auth: "OData + OAuth",
    objects: ["Material master", "Inventory", "Purchase orders", "Plants", "Batch stock"],
    role: "Surfaces surplus and slow-moving material as circular supply.",
    environment: "—",
  },
  {
    id: "dynamics-365",
    name: "Dynamics 365 Supply Chain",
    provider: "Microsoft",
    category: "ERP",
    status: "READY TO CONFIGURE",
    direction: "inbound",
    auth: "OAuth 2.0",
    objects: ["Released products", "On-hand inventory", "Purchase orders", "Warehouses"],
    role: "Alternative ERP source for material and inventory signals.",
    environment: "—",
  },
  {
    id: "oracle-fusion",
    name: "Oracle Fusion Cloud ERP",
    provider: "Oracle",
    category: "ERP",
    status: "READY TO CONFIGURE",
    direction: "inbound",
    auth: "OAuth 2.0",
    objects: ["Items", "Inventory balances", "Procurement", "Cost"],
    role: "Enterprise ERP source for inventory and cost.",
    environment: "—",
  },

  // ── Procurement ─────────────────────────────────────────────────────────
  {
    id: "coupa",
    name: "Coupa",
    provider: "Coupa",
    category: "Procurement",
    status: "DEMO DATA",
    direction: "bidirectional",
    auth: "OAuth 2.0",
    objects: ["Suppliers", "Commodities", "Requisitions", "Purchase orders", "Contracts"],
    role: "Identifies demand-side buyers and category spend for matching.",
    environment: "—",
    writeBack: ["Export opportunity as sourcing request"],
  },
  {
    id: "sap-ariba",
    name: "SAP Ariba",
    provider: "SAP",
    category: "Procurement",
    status: "DEMO DATA",
    direction: "bidirectional",
    auth: "OAuth 2.0",
    objects: ["Suppliers", "Sourcing events", "Contracts", "Spend categories"],
    role: "Demand signals and sourcing-event write-back.",
    environment: "—",
    writeBack: ["Create sourcing event (draft)"],
  },
  {
    id: "jaggaer",
    name: "JAGGAER",
    provider: "JAGGAER",
    category: "Procurement",
    status: "READY TO CONFIGURE",
    direction: "bidirectional",
    auth: "API key",
    objects: ["Suppliers", "Sourcing", "Contracts"],
    role: "Source-to-contract demand signals.",
    environment: "—",
  },
  {
    id: "ivalua",
    name: "Ivalua",
    provider: "Ivalua",
    category: "Procurement",
    status: "READY TO CONFIGURE",
    direction: "inbound",
    auth: "API key",
    objects: ["Suppliers", "Categories", "Purchase orders"],
    role: "Spend and supplier data for demand matching.",
    environment: "—",
  },

  // ── CRM ───────────────────────────────────────────────────────────────────
  {
    id: "salesforce",
    name: "Salesforce",
    provider: "Salesforce",
    category: "CRM",
    status: "READY TO CONFIGURE",
    direction: "bidirectional",
    auth: "OAuth 2.0",
    objects: ["Accounts", "Contacts", "Opportunities", "Tasks"],
    role: "Manages engagement, ownership and deal stage for opportunities.",
    environment: "—",
    writeBack: ["Create engagement", "Create opportunity", "Log next step"],
  },
  {
    id: "dynamics-crm",
    name: "Dynamics 365 Sales",
    provider: "Microsoft",
    category: "CRM",
    status: "READY TO CONFIGURE",
    direction: "bidirectional",
    auth: "OAuth 2.0",
    objects: ["Accounts", "Contacts", "Opportunities", "Activities"],
    role: "CRM engagement and relationship ownership.",
    environment: "—",
    writeBack: ["Create engagement", "Create opportunity"],
  },

  // ── Organisation Intelligence ─────────────────────────────────────────────
  {
    id: "companies-house",
    name: "Companies House",
    provider: "GOV.UK",
    category: "Organisation Intelligence",
    status: "DEMO DATA",
    direction: "inbound",
    auth: "API key",
    objects: ["Company profile", "Company number", "SIC codes", "Status", "Registered office", "Officers"],
    role: "Verifies organisation identity and enriches profiles.",
    environment: "Sandbox",
    note: "Free public API — sandbox available to configure.",
  },
  {
    id: "opencorporates",
    name: "OpenCorporates",
    provider: "OpenCorporates",
    category: "Organisation Intelligence",
    status: "API ACCESS REQUIRED",
    direction: "inbound",
    auth: "API key",
    objects: ["Company records", "Jurisdictions", "Officers"],
    role: "Cross-jurisdiction corporate verification.",
    environment: "—",
    note: "Requires an API token.",
  },

  // ── Waste Data ─────────────────────────────────────────────────────────
  {
    id: "sepa",
    name: "SEPA Waste Data",
    provider: "Scottish Environment Protection Agency",
    category: "Waste Data",
    status: "DEMO DATA",
    direction: "inbound",
    auth: "API key",
    objects: ["Waste from all sources", "Household waste", "Landfill", "Incineration", "Categories"],
    role: "Regional waste context and disposal-cost benchmarks.",
    environment: "—",
    note: "Aggregate open data — used as context/benchmark, not business-level data.",
  },

  // ── Carbon ────────────────────────────────────────────────────────────────
  {
    id: "climatiq",
    name: "Climatiq",
    provider: "Climatiq",
    category: "Carbon",
    status: "DEMO DATA",
    direction: "inbound",
    auth: "API key",
    objects: ["Emission factors", "Estimates", "Freight factors"],
    role: "Calculates avoided and transport emissions per opportunity.",
    environment: "Sandbox",
    note: "Free tier available to configure.",
  },
  {
    id: "defra-factors",
    name: "UK Government / DEFRA factors",
    provider: "DESNZ / DEFRA",
    category: "Carbon",
    status: "READY TO CONFIGURE",
    direction: "inbound",
    auth: "API key",
    objects: ["Conversion factors"],
    role: "Annual UK conversion factors for emissions.",
    environment: "—",
    note: "Open dataset — importable.",
  },
  {
    id: "ecoinvent",
    name: "ecoinvent",
    provider: "ecoinvent",
    category: "Carbon",
    status: "API ACCESS REQUIRED",
    direction: "inbound",
    auth: "API key",
    objects: ["LCA datasets"],
    role: "Premium life-cycle datasets for enterprise deployments.",
    environment: "—",
    note: "Premium dataset — licence required.",
  },

  // ── Logistics ─────────────────────────────────────────────────────────────
  {
    id: "openrouteservice",
    name: "OpenRouteService",
    provider: "HeiGIT",
    category: "Logistics",
    status: "DEMO DATA",
    direction: "inbound",
    auth: "API key",
    objects: ["Routes", "Distance matrix", "HGV profiles"],
    role: "Supplier → buyer distance and freight routing.",
    environment: "—",
  },
  {
    id: "mapbox",
    name: "Mapbox",
    provider: "Mapbox",
    category: "Logistics",
    status: "READY TO CONFIGURE",
    direction: "inbound",
    auth: "API key",
    objects: ["Directions", "Matrix", "Geocoding"],
    role: "Routing and geocoding for logistics estimates.",
    environment: "—",
  },
  {
    id: "google-maps",
    name: "Google Maps Platform",
    provider: "Google",
    category: "Logistics",
    status: "READY TO CONFIGURE",
    direction: "inbound",
    auth: "API key",
    objects: ["Distance Matrix", "Routes", "Geocoding"],
    role: "Enterprise routing and distance.",
    environment: "—",
  },

  // ── Marketplaces ────────────────────────────────────────────────────────
  {
    id: "cyrkl",
    name: "Cyrkl",
    provider: "Cyrkl",
    category: "Marketplaces",
    status: "API ACCESS REQUIRED",
    direction: "bidirectional",
    auth: "Partnership agreement",
    objects: ["Listings", "Demand requests", "Offers"],
    role: "List surplus material and discover external demand.",
    environment: "—",
    note: "Partnership connector — marketplace adapter available.",
    writeBack: ["Publish listing", "Import demand"],
  },
  {
    id: "globechain",
    name: "Globechain",
    provider: "Globechain",
    category: "Marketplaces",
    status: "API ACCESS REQUIRED",
    direction: "bidirectional",
    auth: "Partnership agreement",
    objects: ["Listings", "Members", "Reuse records"],
    role: "Reuse marketplace for assets and materials.",
    environment: "—",
    note: "Partnership connector — marketplace adapter available.",
  },
  {
    id: "excess-materials-exchange",
    name: "Excess Materials Exchange",
    provider: "EME",
    category: "Marketplaces",
    status: "API ACCESS REQUIRED",
    direction: "bidirectional",
    auth: "Partnership agreement",
    objects: ["Material listings", "Matches", "Value & impact"],
    role: "Material exchange and valuation.",
    environment: "—",
    note: "Partnership connector — marketplace adapter available.",
  },

  // ── Data Warehouses ───────────────────────────────────────────────────────
  {
    id: "snowflake",
    name: "Snowflake",
    provider: "Snowflake",
    category: "Data Warehouses",
    status: "READY TO CONFIGURE",
    direction: "bidirectional",
    auth: "Service account",
    objects: ["Shares", "Tables", "Streams"],
    role: "Read enterprise material data and publish opportunity marts.",
    environment: "—",
  },
  {
    id: "databricks",
    name: "Databricks",
    provider: "Databricks",
    category: "Data Warehouses",
    status: "READY TO CONFIGURE",
    direction: "bidirectional",
    auth: "Service account",
    objects: ["Unity Catalog", "Delta tables"],
    role: "Lakehouse source and model outputs.",
    environment: "—",
  },
  {
    id: "microsoft-fabric",
    name: "Microsoft Fabric",
    provider: "Microsoft",
    category: "Data Warehouses",
    status: "READY TO CONFIGURE",
    direction: "bidirectional",
    auth: "OAuth 2.0",
    objects: ["OneLake", "Lakehouse", "Warehouse"],
    role: "Fabric OneLake source and sink.",
    environment: "—",
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    id: "power-bi",
    name: "Power BI",
    provider: "Microsoft",
    category: "Analytics",
    status: "READY TO CONFIGURE",
    direction: "outbound",
    auth: "OAuth 2.0",
    objects: ["Datasets", "Dataflows"],
    role: "Publish opportunity and impact models to executives.",
    environment: "—",
  },
  {
    id: "tableau",
    name: "Tableau",
    provider: "Salesforce",
    category: "Analytics",
    status: "READY TO CONFIGURE",
    direction: "outbound",
    auth: "Service account",
    objects: ["Published data sources", "Workbooks"],
    role: "Executive analytics distribution.",
    environment: "—",
  },
];

export const CONNECTOR_BY_ID = new Map(CONNECTORS.map((c) => [c.id, c]));

// ── Commercial Data Graph ───────────────────────────────────────────────────
export const GRAPH_NODES: GraphNode[] = [
  { id: "erp", label: "SAP · Oracle · Dynamics", sublabel: "ERP", kind: "source", col: 0, row: 1 },
  { id: "supply", label: "Material supply", sublabel: "surplus, slow-moving", kind: "source", col: 1, row: 1 },
  { id: "circa", label: "CIRCA", sublabel: "intelligence layer", kind: "core", col: 2, row: 1 },
  { id: "ch", label: "Companies House", sublabel: "identity", kind: "source", col: 3, row: 0 },
  { id: "sepa", label: "SEPA", sublabel: "market context", kind: "source", col: 3, row: 2 },
  { id: "match", label: "Match engine", sublabel: "supply ↔ demand", kind: "engine", col: 4, row: 1 },
  { id: "procurement", label: "Coupa · Ariba", sublabel: "procurement demand", kind: "source", col: 4, row: 2 },
  { id: "opportunity", label: "Commercial opportunity", kind: "output", col: 5, row: 1 },
  { id: "carbon", label: "Climatiq + logistics", sublabel: "carbon & transport", kind: "source", col: 5, row: 2 },
  { id: "value", label: "Net economic + environmental value", kind: "output", col: 6, row: 1 },
  { id: "crm", label: "CRM · sourcing · pilot", sublabel: "action", kind: "output", col: 6, row: 2 },
];

export const GRAPH_EDGES: GraphEdge[] = [
  { from: "erp", to: "supply" },
  { from: "supply", to: "circa" },
  { from: "ch", to: "circa" },
  { from: "sepa", to: "circa" },
  { from: "circa", to: "match" },
  { from: "procurement", to: "match" },
  { from: "match", to: "opportunity" },
  { from: "carbon", to: "opportunity" },
  { from: "opportunity", to: "value" },
  { from: "value", to: "crm" },
];
